package com.shyxseek.app.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.navigation.compose.*
import com.shyxseek.app.domain.MessageRole
import com.shyxseek.app.ui.chat.ChatViewModel
import com.shyxseek.app.ui.screens.*

@Composable fun ShyxSeekApp(){
 val nav=rememberNavController(); Scaffold(bottomBar={NavigationBar{listOf("chat" to Icons.Default.Chat,"knowledge" to Icons.Default.School,"memory" to Icons.Default.Memory,"projects" to Icons.Default.Folder,"settings" to Icons.Default.Settings).forEach{(r,i)->NavigationBarItem(selected=false,onClick={nav.navigate(r){launchSingleTop=true}},icon={Icon(i,null)},label={Text(r.replaceFirstChar{it.uppercase()})})}}}){pad->
 NavHost(nav,"chat",Modifier.padding(pad)){composable("chat"){ChatScreen()};composable("knowledge"){KnowledgeScreen()};composable("memory"){MemoryScreen()};composable("projects"){ProjectsScreen()};composable("settings"){SettingsScreen()}}
 }}
@Composable fun ChatScreen(vm:ChatViewModel=hiltViewModel()){val s by vm.state.collectAsState();Column(Modifier.fillMaxSize().padding(12.dp)){Text("ShyxSeek",style=MaterialTheme.typography.headlineSmall);Spacer(Modifier.height(8.dp));LazyColumn(Modifier.weight(1f)){items(s.messages){m->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(12.dp)){Text(if(m.role==MessageRole.USER)"Você" else "ShyxSeek",style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.primary);Text(m.content)}}};if(s.generating){item{LinearProgressIndicator(Modifier.fillMaxWidth())}}};s.error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Row{OutlinedTextField(s.draft,vm::draft,Modifier.weight(1f),placeholder={Text("Mensagem...")},maxLines=5);Spacer(Modifier.width(8.dp));FilledIconButton(onClick={if(s.generating)vm::stop else vm::send}){Icon(if(s.generating)Icons.Default.Stop else Icons.Default.Send,null)}}}}
@Composable fun KnowledgeScreen(vm:KnowledgeViewModel=hiltViewModel()){val items by vm.items.collectAsState();var topic by remember{mutableStateOf("")};var text by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Conhecimento",style=MaterialTheme.typography.headlineSmall);OutlinedTextField(topic,{topic=it},label={Text("Tópico")},modifier=Modifier.fillMaxWidth());OutlinedTextField(text,{text=it},label={Text("Ensino")},modifier=Modifier.fillMaxWidth());Button(onClick={vm.teach(topic,text);text=""},enabled=text.isNotBlank()){Text("Aprender")};LazyColumn{items(items){Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(12.dp)){Text(it.topic,color=MaterialTheme.colorScheme.primary);Text(it.content)}}}}}}
@Composable fun MemoryScreen(vm:MemoryViewModel=hiltViewModel()){val items by vm.items.collectAsState();var text by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Memória",style=MaterialTheme.typography.headlineSmall);OutlinedTextField(text,{text=it},label={Text("Lembre que...")},modifier=Modifier.fillMaxWidth());Button(onClick={vm.remember(text);text=""},enabled=text.isNotBlank()){Text("Salvar memória")};LazyColumn{items(items){Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(12.dp)){Text(it.memoryType.name,color=MaterialTheme.colorScheme.primary);Text(it.content)}}}}}}
@Composable fun ProjectsScreen(vm:ProjectsViewModel=hiltViewModel()){val items by vm.items.collectAsState();Column(Modifier.fillMaxSize().padding(16.dp)){Text("Projetos",style=MaterialTheme.typography.headlineSmall);LazyColumn{items(items){Card(Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(14.dp)){Text(it.name,style=MaterialTheme.typography.titleMedium);Text(it.status);if(it.goal.isNotBlank())Text(it.goal)}}}}}}
@Composable fun SettingsScreen(vm:SettingsViewModel=hiltViewModel()){val s by vm.state.collectAsState();var provider by remember(s.provider){mutableStateOf(s.provider)};var base by remember(s.baseUrl){mutableStateOf(s.baseUrl)};var model by remember(s.model){mutableStateOf(s.model)};var key by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Ajustes de IA",style=MaterialTheme.typography.headlineSmall);Row{FilterChip(provider=="fake",{provider="fake"},{Text("Fake offline")});Spacer(Modifier.width(8.dp));FilterChip(provider=="openai_compatible",{provider="openai_compatible"},{Text("OpenAI Compatible")})};OutlinedTextField(base,{base=it},label={Text("Base URL")},modifier=Modifier.fillMaxWidth(),enabled=provider!="fake");OutlinedTextField(model,{model=it},label={Text("Modelo")},modifier=Modifier.fillMaxWidth(),enabled=provider!="fake");OutlinedTextField(key,{key=it},label={Text(if(s.hasApiKey)"API key (já salva; preencha para trocar)" else "API key")},modifier=Modifier.fillMaxWidth(),enabled=provider!="fake");Button(onClick={vm.save(provider,base,model,key)}){Text("Salvar")};Spacer(Modifier.height(16.dp));Text("Privacidade: sem analytics, sem anúncios e sem upload automático. Chaves são criptografadas via Android Keystore.")}}
